name: build

on:
  push:
    branches:
      - main

jobs:
  build-customer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter (Customer)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'   # Customer app is fine on 3.19.0

      - name: Install dependencies
        run: |
          cd customer_app/customer
          flutter pub get

      - name: Build Customer App
        run: |
          cd customer_app/customer
          flutter build apk --release

      - name: Upload Customer APK
        uses: actions/upload-artifact@v4
        with:
          name: customer-app
          path: customer_app/customer/build/app/outputs/flutter-apk/app-release.apk

  build-admin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
