name: Build Omkar Travels APKs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip all zips
        run: |
          for file in *.zip; do
            dir="${file%.zip}"
            rm -rf "$dir"
            unzip -o "$file" -d "$dir"
            rm "$file"
          done

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6

      - name: Build all Flutter projects
        run: |
          find . -name "pubspec.yaml" | while read yaml; do
            proj=$(dirname "$yaml")
            echo "🚀 Building project in $proj"
            cd "$proj"
            flutter pub get
            flutter build apk --release
            cd -
          done

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: all-apks
          path: "**/build/app/outputs/flutter-apk/*.apk"
