name: Build Omkar Apps

on:
  workflow_dispatch:

jobs:
  build-customer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Build Customer APK
        run: |
          cd customer
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: OmkarCustomerAPK
          path: customer/build/app/outputs/flutter-apk/app-release.apk

  build-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - name: Build Admin APK
        run: |
          cd admin
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: OmkarAdminAPK
          path: admin/build/app/outputs/flutter-apk/app-release.apk
