name: Build Omkar Travels APKs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6

      - name: Build Customer App
        working-directory: customer_app
        run: |
          flutter pub get
          flutter build apk --release

      - name: Upload Customer APK
        uses: actions/upload-artifact@v4
        with:
          name: customer-app
          path: customer_app/build/app/outputs/flutter-apk/app-release.apk

      - name: Build Admin App
        working-directory: admin_app
        run: |
          flutter pub get
          flutter build apk --release

      - name: Upload Admin APK
        uses: actions/upload-artifact@v4
        with:
          name: admin-app
          path: admin_app/build/app/outputs/flutter-apk/app-release.apk
