name: Build Omkar Travels Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      # -------------------------------
      # UNZIP PROJECTS
      # -------------------------------
      - name: Unzip admin app
        run: |
          if [ -f admin_app.zip ]; then
            rm -rf admin_app
            unzip -o admin_app.zip -d admin_app
            rm admin_app.zip
          fi

      - name: Unzip customer app
        run: |
          if [ -f customer_app.zip ]; then
            rm -rf customer_app
            unzip -o customer_app.zip -d customer_app
            rm customer_app.zip
          fi

      - name: Unzip www
        run: |
          if [ -f www.zip ]; then
            rm -rf www
            unzip -o www.zip -d www
            rm www.zip
          fi

      - name: Unzip
